name: action-test
on:
  push: []
  schedule:
  - cron: 59 14 * * *
  pull_request: []

jobs:
  test:
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - macos-10.15
        - macos-11
        - windows-2016
        - windows-2019
        - windows-2022
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: psf/black@stable
    - uses: ./
      with:
        token: ${{ secrets.SUBMODULE_UPDATER_GH_TOKEN }}
        committer: >-
          Submodule Updater <engineering+submodule-updater@planetariumhq.com>
        targets: |
          planetarium/lib9c:main
          planetarium/NineChronicles:main
        dry-run: true
